# 로컬 유레카 환경
server:
  port: 10238

eureka:
  client:
    fetch-registry: true # Eureka에서 다른 서비스 정보를 받아올지 여부
    register-with-eureka: true # 현재 애플리케이션을 Eureka에 등록할지 여부
    service-url:
      defaultZone: http://admin:1234@localhost:10230/eureka # 로컬 Eureka 서버의 주소
  instance:
    prefer-ip-address: true # 서비스 등록 시 도메인 대신 IP 주소로 등록

spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 293

  security:
    oauth2:
      client:
        registration:
          payco:
            client-id: 3RD4qpUi5ZoDO2GNFEnioKX
            client-secret: kAoXi_Yvk8Po1nxrVqpdNIe0
            redirect-uri: "http://localhost:10238/login/oauth2/code/payco"
            authorization-grant-type: authorization_code
            scope: profile
            client-name: PAYCO
        provider:
          payco:
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            user-info-uri: https://apis.payco.com/oauth2.0/user/me
            user-name-attribute: id

order:
  toss:
    client-key: test_ck_pP2YxJ4K87B750wR2XP2rRGZwXLO
    success-url: http://localhost:10238/order/success
    fail-url: http://localhost:10238/order/fail
  admin: http://localhost:10232/api/admin/orders
