# 실서비스 서버
eureka:
  client:
    fetch-registry: true # Eureka에서 다른 서비스 정보를 받아올지 여부
    register-with-eureka: true # 현재 애플리케이션을 Eureka에 등록할지 여부
    service-url:
      defaultZone: http://admin:1234@s1.java21.net:10230/eureka # 로컬 Eureka 서버의 주소
  instance:
    prefer-ip-address: true # 서비스 등록 시 도메인 대신 IP 주소로 등록

member:
  login:
    url: https://e2bs.shop/api/login

  register:
    url: https://e2bs.shop/api/register

auth:
  jwt:
    create:
      url: https://e2bs.shop/api/auth

# 쿠폰 정책
coupon:
  policy:
    url: http://e2bs.shop/api/admin/couponPolicies

# 주문
order:
  create:
    url: https://e2bs.shop/api/createOrder

  confirm:
    url: https://e2bs.shop/api/orderConfirm