servlet:
  session:
    cookie:
      same-site: none
      secure: true

# 공통 설정
spring:
  application:
    name: FRONT

  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:10240 # config 서버 연결

  mvc:
    hidden method:
      filter:
        enabled: true

  session:
    timeout: 3600s             # 세션 만료 시간 (초 단위)
    redis:
      namespace: e2bs:sessions # Redis 키 prefix 커스터마이징

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 294

  mail:
    host: smtp.gmail.com
    port: 587
    username: e2bsshop
    password: szuxvsakflliulcx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Ribbon 비활성화 (Spring Cloud LoadBalancer 사용)
      configurations:
        default:
          type: RoundRobin

server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true

  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*" # Actuator 의 모든 엔드포인트를 웹에서 노출 (운영환경에선 최소화 필요)

custom:
  oauth2:
    payco-callback-path: /login/oauth2/code/payco/**

dooray:
  authentication:
    url: https://nhnacademy.dooray.com/services