# 로컬 유레카 환경
server:
  port: 10238

eureka:
  client:
    fetch-registry: true # Eureka에서 다른 서비스 정보를 받아올지 여부
    register-with-eureka: true # 현재 애플리케이션을 Eureka에 등록할지 여부
    service-url:
      defaultZone: http://admin:1234@localhost:10230/eureka # 로컬 Eureka 서버의 주소
  instance:
    prefer-ip-address: true # 서비스 등록 시 도메인 대신 IP 주소로 등록

spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 293


member:
  url: http://localhost:10232/api/members
  login:
    url: http://localhost:10232/api/login

  register:
    url: http://localhost:10232/api/register

  mypage:
    url: http://localhost:10232/api/mypage

auth:
  jwt:
    create:
      url:
        http://localhost:10232/api/auth

# 쿠폰
coupon:
  url: http://localhost:10232/api/admin/coupons
  policy:
    url: http://localhost:10232/api/admin/couponPolicies
  member:
    url: http://localhost:10232/api/admin/member-coupons
  box:
    url: http://localhost:10232/api/member-coupons

# 상품 - 출판사, 기여자 역할
product:
  url: http://localhost:10232/api/products
  publisher:
    url: http://localhost:10232/api/admin/publishers

  contributor:
    position:
      url: http://localhost:10232/api/admin/positions
    url: http://localhost:10232/api/admin/contributors


  tag:
    url: http://localhost:10232/api/admin/tags

  category:
    user:
      url: http://localhost:10232/api/categories
    admin:
      url: http://localhost:10232/api/admin/categories

  book:
    member:
      url: http://localhost:10232/api/books
    admin:
      url: http://localhost:10232/api/admin/books

order:
  wrapper:
    url: http://localhost:10232/api # wrapper adaptor는 사용자 / 관리자 url이 같이 있어서 코드 내부에 있는 Mapping 어노테이션에서 나머지 url을 작성해주었음
  order:
    url: http://localhost:10232/api/order
  delivery:
    admin:
      url: http://localhost:10232/api/admin/deliveryFee
    user:
      url: http://localhost:10232/api/deliveryFee

  toss:
    client-key: test_ck_pP2YxJ4K87B750wR2XP2rRGZwXLO
    success-url: http://localhost:10238/order/success
    fail-url: http://localhost:10238/order/fail
  admin: http://localhost:10232/api/admin/orders

customer:
  url: http://localhost:10232/api/customers
guest:
  url: http://localhost:10232/api/guests

review:
  url: http://localhost:10232/api/reviews

index:
  url: http://localhost:10232/api