# 로컬 유레카 환경
server:
  port: 10238

eureka:
  client:
    fetch-registry: true # Eureka에서 다른 서비스 정보를 받아올지 여부
    register-with-eureka: true # 현재 애플리케이션을 Eureka에 등록할지 여부
    service-url:
      defaultZone: http://admin:1234@localhost:10230/eureka # 로컬 Eureka 서버의 주소
  instance:
    prefer-ip-address: true # 서비스 등록 시 도메인 대신 IP 주소로 등록

member:
  login:
    url: http://localhost:10232/api/login

  register:
    url: http://localhost:10232/api/register

auth:
  jwt:
    create:
      url:
        http://localhost:10232/api/auth

# 쿠폰 정책
coupon:
  policy:
    url: http://localhost:10232/api/admin/couponPolicies

# 상품 - 출판사, 기여자 역할
product:
  publisher:
    url: http://localhost:10232/api/admin/publishers

  contributor:
    position:
      url: http://localhost:10236/api/admin/positions
    url: http://localhost:10236/api/admin/contributors


  tag:
    url: http://localhost:10232/api/admin/tags


order:
  wrapper:
    url: http://localhost:10232/api # wrapper adaptor는 사용자 / 관리자 url이 같이 있어서 코드 내부에 있는 Mapping 어노테이션에서 나머지 url을 작성해주었음