servlet:
  session:
    cookie:
      same-site: none
      secure: true

# 공통 설정
spring:
  application:
    name: FRONT

  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:10240 # config 서버 연결

  mvc:
    hidden method:
      filter:
        enabled: true

  session:
    timeout: 3600s             # 세션 만료 시간 (초 단위)
    redis:
      namespace: e2bs:sessions # Redis 키 prefix 커스터마이징

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 294

  mail:
    host: smtp.gmail.com
    port: 587
    username: e2bsshop
    password: szuxvsakflliulcx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace # SQL 파라미터 바인딩 로그를 trace 레벨로 출력
    org.springframework.transaction.interceptor: trace # 트랜잭션 처리 로그를 trace 로 출력

server:
  servlet:
    session:
      cookie:
        same-site: None
        secure: true

  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*" # Actuator 의 모든 엔드포인트를 웹에서 노출 (운영환경에선 최소화 필요)

member:
  login:
    url: http://localhost:10232/api/login

  register:
    url: http://localhost:10232/api/register

  state:
    url: http://localhost:10232/api/members

  dormant:
    url: http://localhost:10232/api/dormant

customer:
  login:
    url: http://localhost:10232/api/customers/login

  register:
    url: http://localhost:10232/api/customers/register

oauth:
  login:
    url: http://localhost:10232/api/oauth/login

  register:
    url: http://localhost:10232/api/oauth/register

token:
  create:
    url: http://localhost:10232/api/token

# 쿠폰
coupon:
  url: http://localhost:10232/api/admin/coupons

  policy:
    url: http://localhost:10232/api/admin/couponPolicies

  member:
    url: http://localhost:10232/api/admin/memberCoupons

  order:
    url: http://localhost:10232/api/order

point:
  admin:
    url: http://localhost:10232/api/admin/pointPolicies

# 상품 - 출판사, 기여자 역할
product:
  url: http://localhost:10232/api/products

  publisher:
    url: http://localhost:10232/api/admin/publishers

  contributor:
    position:
      url: http://localhost:10232/api/admin/positions

    url: http://localhost:10232/api/admin/contributors

  tag:
    url: http://localhost:10232/api/admin/tags

  category:
    user:
      url: http://localhost:10232/api/categories

    admin:
      url: http://localhost:10232/api/admin/categories

  book:
    member:
      url: http://localhost:10232/api/books

    admin:
      url: http://localhost:10232/api/admin/books

  productState:
    url: http://localhost:10232/api/productState

order:
  wrapper:
    url: http://localhost:10232/api # wrapper adaptor는 사용자 / 관리자 url이 같이 있어서 코드 내부에 있는 Mapping 어노테이션에서 나머지 url을 작성해주었음

  order:
    auth: http://localhost:10232/api/auth/orders
    url: http://localhost:10232/api/orders # 비인증 주문 관련 -> 비회원 용 요청

  admin: http://localhost:10232/api/auth/admin/orders

  delivery:
    admin:
      url: http://localhost:10232/api/admin/deliveryFee

    user:
      url: http://localhost:10232/api/deliveryFee

cart:
  url: http://localhost:10232/api/carts

guest:
  url: http://localhost:10232/api/guests

review:
  url: http://localhost:10232/api/reviews

index:
  url: http://localhost:10232/api

# 인증이 필요한 url
auth:
  member:
    mypage:
      url: http://localhost:10232/api/auth/mypage

    url: http://localhost:10232/api/auth/members

  home:
    member:
      name:
        url: http://localhost:10232/api/auth/home

  admin:
    settings:
      url: http://localhost:10232/api/auth/admin/settings


dooray:
  authentication:
    url: https://nhnacademy.dooray.com/services